import { institutionCoverage } from '../src/data/institutionCoverage.ts';

console.log('=== UniScoreVN Coverage ===');
console.log('');
console.log('Catalog');
console.log('-------');
console.log(`Total entries:                       ${institutionCoverage.totalCatalogEntries}`);
console.log(`Independent education institutions:  ${institutionCoverage.independentEducationInstitutions}`);
console.log(`Internal entities:                   ${institutionCoverage.internalUnitEntries}`);
console.log('');
console.log('By level/type');
console.log('-------------');
console.log(`University / university-level:       ${institutionCoverage.universityInstitutions}`);
console.log(`Academies:                           ${institutionCoverage.academies}`);
console.log(`Pedagogical colleges:                ${institutionCoverage.pedagogicalColleges}`);
console.log(`Vocational colleges:                 ${institutionCoverage.vocationalColleges}`);
console.log(`Other independent types:             ${institutionCoverage.otherIndependentInstitutions}`);
console.log('');
console.log('Calculator coverage');
console.log('-------------------');
console.log(`Admission data available:            ${institutionCoverage.admissionDataAvailable}`);
console.log(`Verified calculators:                ${institutionCoverage.fullyVerified}`);
console.log(`Partial:                             ${institutionCoverage.partialCalculator}`);
console.log(`Eligibility only:                    ${institutionCoverage.eligibilitySupported}`);
console.log(`Catalog only:                        ${institutionCoverage.catalogOnly}`);
